apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: crd.hector.dev/v1
kind: SharedPVC
metadata:
  labels:
    app.kubernetes.io/name: k8s-shared-pvc
    app.kubernetes.io/managed-by: kustomize
  name: sharedpvc-sample
spec:
  # TODO(user): Add fields here
  image: "docker.registry/myimage:latest" 
  newpvc:
    originalpvcname: "hector-pvc" 
    originalnamespace: "test" 
    targetpvcname: "target-pvc" 
    targetnamespace: "default" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hector-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: hector-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hector-pv
  namespace: test
spec:
  capacity:
    storage: 1Gi
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/