apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: test
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - mountPath: /mnt/data
      name: hector-storage
  volumes:
  - name: hector-storage
    persistentVolumeClaim:
      claimName: hector-pvc
